# Catppuccin Mocha colors
exec = gsettings set org.gnome.desktop.interface gtk-theme 'catppuccin-mocha-mauve-standard+default'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec = gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-dracula'
exec = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'

general {
    col.active_border = rgba(cba6f7ff) rgba(f5c2e7ff) 45deg
    col.inactive_border = rgba(313244cc) rgba(45475acc) 45deg
}

group {
    col.border_active = rgba(cba6f7ff) rgba(f5c2e7ff) 45deg
    col.border_inactive = rgba(313244cc) rgba(45475acc) 45deg
    col.border_locked_active = rgba(f5c2e7ff) rgba(cba6f7ff) 45deg
    col.border_locked_inactive = rgba(45475acc) rgba(313244cc) 45deg
}
