$scrPath = $HOME/.local/share/bin
$term = kitty
$file = thunar
$browser = zen-browser
$mail = thunderbird

# Sources
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/themes/common.conf
source = ~/.config/hypr/themes/theme.conf
source = ~/.config/hypr/themes/colors.conf
source = ~/.config/hypr/themes/Wall-Dcol.conf

input {
    kb_layout = latam
    numlock_by_default = true
    follow_mouse = 1
    mouse_refocus = false
    sensitivity = 0
    force_no_accel = 1

    touchpad {
        natural_scroll = yes
        disable_while_typing = false
        clickfinger_behavior = true
    }
}

device {
    name = epic mouse V1
    sensitivity = -0.5
}

# Gestures (Hyprland 0.51+ syntax)
gestures {
    gesture = 3, horizontal, workspace
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_status = master
}

misc {
    vrr = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
}

xwayland {
    force_zero_scaling = true
}
